<Project>
  <PropertyGroup>
    <Authors>HansJack;VSCN-Studio</Authors>
    <Company>Vintage Story CN Studio</Company>
    <Product>LauncherGo</Product>
    <Copyright>Copyright (C) 2026 HansJack, LauncherGo project owner; member of VSCN-Studio</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/vscn-studio/LauncherGo</RepositoryUrl>
  </PropertyGroup>
</Project>
