namespace LauncherGo.Domains.Models;

/// <summary>
///     世界规则目录。规则 key、取值和默认值对齐 VS 1.22.x Survival 的 worldConfigAttributes。
/// </summary>
public static class WorldRuleCatalog
{
    public static IReadOnlyList<WorldRuleDefinition> DefaultRules { get; } =
    [
        Choice("gameMode", "游戏模式", "Game Mode",
            ["survival", "creative"],
            ["Survival", "Creative"], "survival"),
        Choice("playerlives", "玩家生命次数", "Player Lives",
            ["1", "2", "3", "4", "5", "10", "20", "-1"],
            ["1", "2", "3", "4", "5", "10", "20", "infinite"], "-1"),
        Choice("startingClimate", "起始气候", "Starting Climate",
            ["hot", "warm", "temperate", "cool", "icy"],
            ["Hot (28-32°C)", "Warm (19-23 °C)", "Temperate (6-14 °C)", "Cool (-5 to 1 °C)", "Icy (-15 to -10°C)"],
            "temperate"),
        Choice("spawnRadius", "随机重生距离", "Random Respawn Radius",
            ["10000", "5000", "2500", "1000", "500", "250", "100", "50", "25", "0"],
            ["10000 blocks", "5000 blocks", "2500 blocks", "1000 blocks", "500 blocks", "250 blocks", "100 blocks", "50 blocks", "25 blocks", "0 blocks"],
            "50"),
        Choice("graceTimer", "开局保护", "Grace Timer",
            ["10", "5", "4", "3", "2", "1", "0"],
            ["10 days before monsters appear", "5 days before monsters appear", "4 days before monsters appear", "3 days before monsters appear", "2 days before monsters appear", "1 day before monsters appear", "No timer. Monsters spawn right away."],
            "0"),
        Choice("deathPunishment", "死亡惩罚", "Death Punishment",
            ["drop", "keep"],
            ["Drop inventory contents", "Keep inventory contents"], "drop"),
        Choice("droppedItemsTimer", "掉落物清理计时", "Timer For Items Dropped On Death",
            ["300", "600", "1200", "1800", "3600"],
            ["5 minutes", "10 minutes", "20 minutes", "30 minutes", "1 hour"], "600"),

        Choice("seasons", "季节", "Seasons",
            ["enabled", "spring", "summer", "fall", "winter"],
            ["Enabled", "Off, always spring", "Off, always summer", "Off, always fall", "Off, always winter"], "enabled"),
        Choice("daysPerMonth", "每月天数", "Days Per Month",
            ["30", "20", "12", "9", "6", "3"],
            ["30 days (24 real life hours)", "20 days (16 real life hours)", "12 days (9.6 real life hours)", "9 days (7.2 real life hours)", "6 days (4.8 real life hours)", "3 days (2.4 real life hours)"],
            "9"),
        Choice("harshWinters", "真实冬天", "True Winters",
            ["true", "false"],
            ["Enabled", "Disabled"], "true"),
        Choice("blockGravity", "重力方块", "Block Gravity",
            ["sandgravel", "sandgravelsoil"],
            ["Sand and gravel", "Sand, gravel and soil with sideways instability"], "sandgravel"),
        Choice("caveIns", "塌陷", "Cave-Ins",
            ["off", "on"],
            ["Disabled", "Enabled"], "off"),
        Bool("allowFallingBlocks", "允许掉落方块", "Allow Falling Blocks", "true"),
        Bool("allowFireSpread", "允许火焰蔓延", "Allow Fire Spread", "true"),
        Bool("lightningFires", "雷击火焰", "Fire From Lightning", "false"),
        Bool("allowUndergroundFarming", "允许地下耕作", "Allow Underground Farming", "false"),
        Bool("noLiquidSourceTransport", "禁止使用水桶转移液体源", "Prevent Liquid Source Transport By Buckets", "false"),
        Choice("playerHealthPoints", "玩家生命值", "Player Health Points",
            ["5", "10", "15", "20", "25", "30", "35"],
            ["5 hp", "10 hp", "15 hp", "20 hp", "25 hp", "30 hp", "35 hp"], "15"),
        Choice("playerHealthRegenSpeed", "生命恢复率", "Health Regeneration Rate",
            ["2", "1.5", "1.25", "1", "0.75", "0.5", "0.25"],
            ["Very fast (200%)", "Fast (150%)", "Slightly faster (125%)", "Normal (100%)", "Slightly slower (75%)", "Slower (50%)", "Much slower (25%)"],
            "1"),
        Choice("playerHungerSpeed", "饥饿速度", "Hunger Rate",
            ["2", "1.5", "1.25", "1", "0.75", "0.5", "0.25"],
            ["Very fast (200%)", "Fast (150%)", "Slightly faster (125%)", "Normal (100%)", "Slightly slower (75%)", "Slower (50%)", "Much slower (25%)"],
            "1"),
        Choice("lungCapacity", "肺活量", "Lung Capacity",
            ["10000", "20000", "30000", "40000", "60000", "120000", "3600000"],
            ["10 seconds", "20 seconds", "30 seconds", "40 seconds", "60 seconds", "2 minutes", "60 minutes"], "40000"),
        Choice("bodyTemperatureResistance", "身体耐寒度", "Body Temperature Resistance",
            ["-40", "-30", "-25", "-20", "-15", "-10", "-5", "0", "5", "10", "15", "20"],
            ["-40", "-30", "-25", "-20", "-15", "-10", "-5", "0", "5", "10", "15", "20"], "0"),
        Choice("playerMoveSpeed", "行走速度", "Walk Speed",
            ["2", "1.75", "1.5", "1.25", "1", "0.75"],
            ["Fast", "Slightly faster", "Normal", "Slightly slower", "Slower", "Much slower"], "1.5"),
        Choice("creatureHostility", "生物敌对", "Creature Hostility",
            ["aggressive", "passive", "off"],
            ["Aggressive", "Passive", "Never hostile"], "aggressive"),
        Choice("creatureStrength", "生物强度", "Creature Strength",
            ["4", "2", "1.5", "1", "0.5", "0.25"],
            ["Deadly (400%)", "Very Strong (200%)", "Strong (150%)", "Normal (100%)", "Weak (50%)", "Very weak (25%)"], "1"),
        Choice("creatureSwimSpeed", "生物游泳速度", "Creature Swim Speed",
            ["0.5", "0.75", "1", "1.25", "1.5", "1.75", "2", "3"],
            ["50%", "75%", "100%", "125%", "150%", "175%", "200%", "300%"], "2"),
        Choice("foodSpoilSpeed", "食物腐烂速度", "Food Spoil Speed",
            ["4", "3", "2", "1.5", "1.25", "1", "0.75", "0.5", "0.25"],
            ["400%", "300%", "200%", "150%", "125%", "100%", "75%", "50%", "25%"], "1"),
        Choice("saplingGrowthRate", "树苗生长时间", "Sapling Growth Rate",
            ["16", "8", "4", "2", "1.5", "1", "0.75", "0.5", "0.25"],
            ["Extremely slow (16x)", "Much slower (8x)", "Slower (4x)", "Somewhat slower (2x)", "Slightly slower (1.5x)", "Normal (1x)", "Slightly faster (0.75x)", "Faster (0.5x)", "Much faster (0.25x)"],
            "1"),
        Choice("toolDurability", "工具耐久度", "Tool Durability",
            ["4", "3", "2", "1.5", "1.25", "1", "0.75", "0.5"],
            ["400%", "300%", "200%", "150%", "125%", "100%", "75%", "50%"], "1"),
        Choice("toolMiningSpeed", "工具挖掘速度", "Tool Mining Speed",
            ["3", "2", "1.5", "1.25", "1", "0.75", "0.5", "0.25"],
            ["300%", "200%", "150%", "125%", "100%", "75%", "50%", "25%"], "1"),
        Choice("propickNodeSearchRadius", "探矿镐节点搜索半径", "Prospecting Pick Node Search Radius",
            ["0", "2", "4", "6", "8"],
            ["Disabled", "2 blocks", "4 blocks", "6 blocks", "8 blocks"], "0"),
        Choice("microblockChiseling", "凿子雕刻", "Microblock Chiseling",
            ["off", "stonewood", "all"],
            ["Off", "Stone and Wood", "Most cubic blocks"], "stonewood"),
        Bool("allowCoordinateHud", "坐标", "Allow Coordinate HUD", "true"),
        Bool("allowMap", "世界地图", "Allow Map", "true"),
        Bool("colorAccurateWorldmap", "颜色精确的世界地图", "Color-Accurate World Map", "false"),
        Bool("loreContent", "传说内容", "Lore Content", "true"),
        Choice("clutterObtainable", "杂物可否获取", "Clutter Obtainable",
            ["ifrepaired", "yes", "no"],
            ["ifrepaired", "yes", "no"], "ifrepaired"),

        Bool("temporalStability", "时空稳态", "Temporal Stability", "true"),
        Choice("temporalStorms", "时空风暴", "Temporal Storm Frequency",
            ["off", "veryrare", "rare", "sometimes", "often", "veryoften"],
            ["Off", "Every 30-40 days, increase strength/frequency by 2.5% each time, capped at +25%", "Approx. every 20-30 days, increase strength/frequency by 5% each time, capped at +50%", "Approx. every 10-20 days, increase strength/frequency by +10% each time, capped at 100%", "Approx. every 5-10 days, increase strength/frequency by 15% each time, capped at +150%", "Approx. every 3-6 days, increase strength/frequency by 20% each time, capped at +200%"],
            "sometimes"),
        Choice("tempstormDurationMul", "时空风暴时长", "Temporal Storm Length",
            ["2", "1.5", "1.25", "1", "0.75", "0.5", "0.25"],
            ["Much longer (200%)", "Longer (150%)", "Slightly longer (125%)", "Normal (100%)", "Slightly shorter (75%)", "Shorter (50%)", "Much Shorter (25%)"],
            "1"),
        Choice("temporalRifts", "时空裂缝", "Temporal Rifts",
            ["off", "invisible", "visible"],
            ["Off", "Invisible", "Visible"], "visible"),
        Choice("temporalGearRespawnUses", "使用时空齿轮设置重生点", "Temporal Gear Respawn Uses",
            ["-1", "20", "10", "5", "4", "3", "2", "1"],
            ["Infinite", "20 times", "10 times", "5 times", "4 times", "3 times", "2 times", "One time"], "1"),
        Choice("temporalStormSleeping", "在时空风暴期间睡眠", "Sleeping During Temporal Storms",
            ["0", "1"],
            ["Disallowed", "Allowed"], "1"),

        Choice("worldClimate", "气候分布", "Climate Distribution",
            ["realistic", "patchy"],
            ["Realistic", "Patchy"], "realistic"),
        Choice("landcover", "陆地覆盖", "Landcover",
            ["0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "0.95", "0.975", "1"],
            ["~0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "95%", "97.5%", "100%"], "0.975"),
        Choice("oceanscale", "陆地覆盖比例", "Landcover Scale",
            ["0.1", "0.25", "0.5", "0.75", "1", "1.25", "1.5", "1.75", "2", "3", "4", "5"],
            ["10%", "25%", "50%", "75%", "100%", "125%", "150%", "175%", "200%", "300%", "400%", "500%"], "5"),
        Choice("upheavelCommonness", "起伏概率", "Upheaval Commonness",
            ["0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1"],
            ["0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%"], "0.3"),
        Choice("geologicActivity", "地质活动", "Geologic Activity",
            ["0", "0.05", "0.1", "0.2", "0.4"],
            ["None", "Rare", "Uncommon", "Common", "Very Common"], "0.05"),
        Choice("landformScale", "地貌比例", "Landform Scale",
            ["0.2", "0.4", "0.6", "0.8", "1.0", "1.2", "1.4", "1.6", "1.8", "2", "3"],
            ["20%", "40%", "60%", "80%", "100%", "120%", "140%", "160%", "180%", "200%", "300%"], "1.0"),
        Choice("worldWidth", "世界宽度", "World Width",
            ["8192000", "4096000", "2048000", "1024000", "600000", "512000", "384000", "256000", "102400", "51200", "25600", "10240", "5120", "1024", "512", "384", "256", "128", "64", "32"],
            ["8 mil blocks", "4 mil blocks", "2 mil blocks", "1 mil blocks", "600k blocks", "512k blocks", "384k blocks", "256k blocks", "102k blocks", "51k blocks", "25k blocks", "10k blocks", "5120 blocks", "1024 blocks", "512 blocks", "384 blocks", "256 blocks", "128 blocks", "64 blocks", "32 blocks"],
            "1024000"),
        Choice("worldLength", "世界长度", "World Length",
            ["8192000", "4096000", "2048000", "1024000", "600000", "512000", "384000", "256000", "102400", "51200", "25600", "10240", "5120", "1024", "512", "384", "256", "128", "64", "32"],
            ["8 mil blocks", "4 mil blocks", "2 mil blocks", "1 mil blocks", "600k blocks", "512k blocks", "384k blocks", "256k blocks", "102k blocks", "51k blocks", "25k blocks", "10k blocks", "5120 blocks", "1024 blocks", "512 blocks", "384 blocks", "256 blocks", "128 blocks", "64 blocks", "32 blocks"],
            "1024000"),
        Choice("worldEdge", "世界边缘", "World Edge",
            ["blocked", "traversable"],
            ["Blocked", "Traversable (Can fall down)"], "traversable"),
        Choice("polarEquatorDistance", "极赤道距离", "Polar-Equator Distance",
            ["800000", "400000", "200000", "100000", "50000", "25000", "15000", "10000", "5000"],
            ["800k blocks", "400k blocks", "200k blocks", "100k blocks", "50k blocks", "25k blocks", "15k blocks", "10k blocks", "5000 blocks"],
            "50000"),
        Choice("storyStructuresDistScaling", "故事结构距离缩放", "Story Structures Distance Scaling",
            ["0.15", "0.25", "0.5", "0.75", "1", "1.5", "2", "3"],
            ["15%", "25%", "50%", "75%", "100%", "150%", "200%", "300%"], "1"),
        Choice("globalTemperature", "全局温度", "Global Temperature",
            ["4", "2", "1.5", "1", "0.75", "0.5", "0.25"],
            ["Scorching hot", "Very hot", "Hot", "Normal", "Cold", "Very Cold", "Snowball earth"], "1"),
        Choice("globalPrecipitation", "全局降水", "Global Precipitation",
            ["4", "2", "1.5", "1", "0.5", "0.25", "0.1"],
            ["Super humid", "Very humid", "Humid", "Normal", "Semi-Arid", "Arid", "Hyperarid"], "1"),
        Choice("globalForestation", "树林与灌木", "Forestation And Shrubs",
            ["1", "0.9", "0.75", "0.5", "0.25", "0", "-0.25", "-0.5", "-0.75", "-0.9", "-1"],
            ["Forest World (+100%)", "Extremely forested (+90%)", "Very highly forested (+75%)", "Highly forested (+50%)", "Somewhat more forest (+25%)", "Normal", "Somewhat less forest (-25%)", "Significantly less forested (-50%)", "Much less forested (-75%)", "Near Tree-less (-90%)", "Tree-less World (-100%)"],
            "0"),
        Choice("globalDepositSpawnRate", "世界范围内矿床生成率", "Global Deposit Spawn Rate",
            ["3", "2", "1.8", "1.6", "1.4", "1.2", "1", "0.8", "0.6", "0.4", "0.2"],
            ["300%", "200%", "180%", "160%", "140%", "120%", "100%", "80%", "60%", "40%", "20%"], "1"),
        Choice("surfaceCopperDeposits", "地表铜矿床出现频率", "Surface Copper Deposits",
            ["1", "0.5", "0.2", "0.12", "0.05", "0.015", "0"],
            ["Very common", "Common", "Uncommon", "Rare", "Very Rare", "Extremly rare", "Never"], "0.12"),
        Choice("surfaceTinDeposits", "地表锡矿床出现频率", "Surface Tin Deposits",
            ["0.5", "0.25", "0.12", "0.03", "0.014", "0.007", "0"],
            ["Very common", "Common", "Uncommon", "Rare", "Very Rare", "Extremly rare", "Never"], "0.007"),
        Bool("snowAccum", "积雪与结冰", "Snow Accumulation And Freezing", "true"),

        Bool("allowLandClaiming", "领地", "Allow Land Claiming", "true"),
        Bool("classExclusiveRecipes", "职业专属合成配方", "Class Exclusive Recipes", "true"),
        Bool("auctionHouse", "拍卖行", "Auction House", "true")
    ];

    private static WorldRuleDefinition Choice(
        string key,
        string labelZh,
        string labelEn,
        IReadOnlyList<string> choices,
        IReadOnlyList<string> names,
        string defaultValue)
    {
        return new WorldRuleDefinition
        {
            Key = key,
            LabelZh = labelZh,
            LabelEn = labelEn,
            Type = WorldRuleType.Choice,
            Choices = choices,
            ChoiceNames = names,
            DefaultValue = defaultValue
        };
    }

    private static WorldRuleDefinition Bool(
        string key,
        string labelZh,
        string labelEn,
        string defaultValue)
    {
        return new WorldRuleDefinition
        {
            Key = key,
            LabelZh = labelZh,
            LabelEn = labelEn,
            Type = WorldRuleType.Boolean,
            DefaultValue = defaultValue
        };
    }
}
